--- #YAML:1.0
name:                JavaScript-SpiderMonkey
version:             0.19
abstract:            Perl interface to the JavaScript Engine
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Data::Dumper:                  0
    Log::Log4perl:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <m@perlmeister.com>
