name: CI

on: [push]

jobs:
  perl-job:
    runs-on: [self-hosted, ${{ matrix.architecture }}]
    container:
      image: perl:${{ matrix.perl-version }}
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - X64
          - ARM
        perl-version:
          - '5.32'
          - 'latest'
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Regular tests
        run: |
            apt update && apt -y install libprotobuf-dev libprotoc-dev
            cpanm --installdeps --notest .
            bin/run-tests
