name: CI

on: [push]

jobs:
  perl-job:
    runs-on: [self-hosted, "${{ matrix.architecture }}" ]
    container:
      image: perl:${{ matrix.perl-version }}
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - X64
          - ARM
        perl-version:
          - '5.32'
          - 'latest'
    name: Perl ${{ matrix.perl-version }}:${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2
      - name: Install libraries and cpm
        run: |
            apt update && apt -y install libprotobuf-dev libprotoc-dev
            cpanm install App::cpm
      - name: Install depedencies
        run: |
            cpm -v --resolver http://cpanproxy/ --configure-timeout 180 --build-timeout 600 --with-cpanfile=./cpanfile
      - name: Run tests
        run: |
            bin/run-tests
